[pytest]
testpaths = tests

python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

norecursedirs = gliner_test maker_model_test venv env .venv .git __pycache__

filterwarnings =
    ignore::DeprecationWarning