name: Build and Release WaveRedact

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false 
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout of the code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Downloading dependecies
        run: |
          python -m pip install uv
          uv venv
          uv pip install maturin
          cd waveredact_core
          uv run maturin develop --release
          cd ..
          uv pip install .
          uv pip install pyinstaller

      - name: Compiling with PyInstaller
        run: uv run pyinstaller waveredact.spec --clean

      - name: Zip and divide in Volumes (Windows)
        if: runner.os == 'Windows'
        run: |
          cd dist
          7z a -v1500m ..\waveredact-${{ github.ref_name }}-windows.zip waveredact\

      - name: Zip and divide in Volumes (Linux)
        if: runner.os == 'Linux'
        run: |
          cd dist
          zip -r -s 1500m ../waveredact-${{ github.ref_name }}-linux.zip waveredact/

      - name: Zip as single Volume (macOS)
        if: runner.os == 'macOS'
        run: |
          cd dist
          zip -r ../waveredact-${{ github.ref_name }}-macOS.zip waveredact/

      - name: Creating Release and Upload Volumes
        uses: softprops/action-gh-release@v2
        with:
          files: waveredact-${{ github.ref_name }}-*.*
          draft: true
          generate_release_notes: true